version: '3'

services:

    mysql:
        container_name: voxus-db
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./docker/mysql:/var/lib/mysql
        networks:
            - app-network

    php:
        container_name: voxus-app
        build:
            context: ./docker/php
        restart: always
        volumes:
             - "./api/:/var/www/html/api"
        links:
            - mysql
        working_dir: /var/www/html/api
        networks:
            - app-network

    nginx:
        container_name: voxus-nginx
        image: nginx:latest
        volumes:
            - "./api:/var/www/html/api"
            - ./docker/nginx/api.local.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
        restart: always
        links:
            - php
        networks:
            - app-network

networks:
  app-network:
    driver: bridge